databases:
  - name: pizzainn
    databaseName: pizza_inn_development
    user: pizza_inn

services:
  - type: web
    name: pizzainn
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pizzainn
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false